spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
open:
  weather:
    name : openweathermap
    url  : https://api.openweathermap.org/
    request:
      value: /data/2.5/weather?q={searchQuery}&units=metric&appid=7a561184ab149bda1aa8900071b80638
      produces: application/json